# Application name
spring.application.name=trainer-hub
jwt.secret=VzQ5bUh3VlJld1YwWDBsVl9zSE55U3A3X0Z2T1JzQ21aSkc5Z0l4T29NPT0=

# ? MySQL database connection settings (for Railway)
spring.datasource.url=jdbc:mysql://trolley.proxy.rlwy.net:15256/railway?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=SayQcIFmPtrxBGsBtBMDYNahKDqTJbtt
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ? JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ? Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anujkumarpandey2727@gmail.com
spring.mail.password=yourpassword
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ? Server
server.port=8080
server.error.include-message=always
